### ISSUE TITLE
Add "take a deep breath" before "step-by-step" Within Prompts

### ISSUE THREAD

**Issue by CosmicInkScribe** [spdustin/ChatGPT-AutoExpert#13]
### Edition
Check one or more:
- [x] Standard Edition
- [x] Developer Edition

**Is your feature request related to a problem? Please describe.**
I found [an article/paper](https://arstechnica.com/information-technology/2023/09/telling-ai-model-to-take-a-deep-breath-causes-math-scores-to-soar-in-study/) and used it to improve my prompts. The results were promising, and it could be a great addition.

**Describe the solution you'd like**
Add the phrase "take a deep breath" before we use the term "step-by-step".

**Describe alternatives you've considered**
N/A

**Additional context**
- https://arstechnica.com/information-technology/2023/09/telling-ai-model-to-take-a-deep-breath-causes-math-scores-to-soar-in-study/

**Comment by spdustin** [comment]
Thanks for the note! I have always included that in evaluations, and found that it didn't significantly affect the model's ability to attend to the steps in the prompts. However, in current evaluations of a new AutoExpert update I'm working on, it _did_ improve (so far, anyway) instructions for some new features, so that phrase is likely to make an appearance in a future update!
